default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ENV['DATABASE_NAME']

test:
  <<: *default
  database: ENV['DATABASE_NAME_TEST']

production:
  <<: *default
  database: ENV['DATABASE_NAME']
